const universities = [
    { "name": "University of the Punjab (PU)", "location": "Lahore, Punjab" },
    { "name": "National University of Sciences and Technology (NUST)", "location": "Islamabad, Federal" },
    { "name": "Lahore University of Management Sciences (LUMS)", "location": "Lahore, Punjab" },
    { "name": "COMSATS Institute of Information Technology (CIIT)", "location": "Islamabad, Federal" },
    { "name": "University of Karachi (UoK)", "location": "Karachi, Sindh" },
    { "name": "Aga Khan University (AKU)", "location": "Karachi, Sindh" },
    { "name": "University of Engineering and Technology (UET) Lahore", "location": "Lahore, Punjab" },
    { "name": "Quaid-i-Azam University (QAU)", "location": "Islamabad, Federal" },
    { "name": "Institute of Business Administration (IBA) Karachi", "location": "Karachi, Sindh" },
    { "name": "University of Agriculture Faisalabad (UAF)", "location": "Faisalabad, Punjab" },
    { "name": "Government College University (GCU) Lahore", "location": "Lahore, Punjab" },
    { "name": "National University of Computer and Emerging Sciences (FAST-NUCES)", "location": "Islamabad, Federal" },
    { "name": "NED University of Engineering and Technology (NEDUET)", "location": "Karachi, Sindh" },
    { "name": "Allama Iqbal Open University (AIOU)", "location": "Islamabad, Federal" },
    { "name": "University of Peshawar (UoP)", "location": "Peshawar, Khyber Pakhtunkhwa" },
    { "name": "Bahauddin Zakariya University (BZU)", "location": "Multan, Punjab" },
    { "name": "Institute of Space Technology (IST)", "location": "Islamabad, Federal" },
    { "name": "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology (GIKI)", "location": "Topi, Khyber Pakhtunkhwa" },
    { "name": "University of Management and Technology (UMT)", "location": "Lahore, Punjab" },
    { "name": "Pakistan Institute of Engineering and Applied Sciences (PIEAS)", "location": "Islamabad, Federal" },
    { "name": "University of Veterinary and Animal Sciences (UVAS)", "location": "Lahore, Punjab" },
    { "name": "Forman Christian College (FCCU)", "location": "Lahore, Punjab" },
    { "name": "Abdul Wali Khan University (AWKU)", "location": "Mardan, Khyber Pakhtunkhwa" },
    { "name": "Iqra University (IU)", "location": "Karachi, Sindh" },
    { "name": "Air University (AU)", "location": "Islamabad, Federal" },
    { "name": "Bahria University (BU)", "location": "Islamabad, Federal" },
    { "name": "Mehran University of Engineering and Technology (MUET)", "location": "Jamshoro, Sindh" },
    { "name": "University of Sargodha (UoS)", "location": "Sargodha, Punjab" },
    { "name": "Fatima Jinnah Women University (FJWU)", "location": "Rawalpindi, Punjab" },
    { "name": "Khyber Medical University (KMU)", "location": "Peshawar, Khyber Pakhtunkhwa" },
    { "name": "Shaheed Zulfiqar Ali Bhutto Institute of Science and Technology (SZABIST)", "location": "Karachi, Sindh" },
    { "name": "Pakistan Institute of Development Economics (PIDE)", "location": "Islamabad, Federal" },
    { "name": "Institute of Business Management (IoBM)", "location": "Karachi, Sindh" },
    { "name": "University of Sindh (UoS)", "location": "Jamshoro, Sindh" },
    { "name": "University of Gujrat (UoG)", "location": "Gujrat, Punjab" },
    { "name": "Islamia University of Bahawalpur (IUB)", "location": "Bahawalpur, Punjab" },
    { "name": "University of Balochistan (UoB)", "location": "Quetta, Balochistan" },
    { "name": "University of Malakand (UoM)", "location": "Chakdara, Khyber Pakhtunkhwa" },
    { "name": "University of Swat (UoS)", "location": "Swat, Khyber Pakhtunkhwa" },
    { "name": "Arid Agriculture University (AAUR)", "location": "Rawalpindi, Punjab" },
    { "name": "University of Azad Jammu and Kashmir (UAJK)", "location": "Muzaffarabad, Azad Jammu and Kashmir" },
    { "name": "Gomal University (GU)", "location": "Dera Ismail Khan, Khyber Pakhtunkhwa" },
    { "name": "International Islamic University Islamabad (IIUI)", "location": "Islamabad, Federal" },
    { "name": "University of Health Sciences (UHS)", "location": "Lahore, Punjab" },
    { "name": "University of Central Punjab (UCP)", "location": "Lahore, Punjab" },
    { "name": "Hamdard University (HU)", "location": "Karachi, Sindh" },
    { "name": "King Edward Medical University (KEMU)", "location": "Lahore, Punjab" },
    { "name": "Jinnah Sindh Medical University (JSMU)", "location": "Karachi, Sindh" },
    { "name": "University of Haripur (UoH)", "location": "Haripur, Khyber Pakhtunkhwa" },
    { "name": "University of Wah (UoW)", "location": "Wah, Punjab" },
    { "name": "Shaheed Benazir Bhutto University (SBBU)", "location": "Sheringal, Khyber Pakhtunkhwa" },
    { "name": "Shaheed Benazir Bhutto Women University (SBBWU)", "location": "Peshawar, Khyber Pakhtunkhwa" },
    { "name": "Virtual University of Pakistan (VU)", "location": "Lahore, Punjab" },
    { "name": "University of Lahore (UoL)", "location": "Lahore, Punjab" },
    { "name": "Karachi School of Business and Leadership (KSBL)", "location": "Karachi, Sindh" },
    { "name": "Institute of Management Sciences (IMS)", "location": "Lahore, Punjab" },
    { "name": "University of Education (UE)", "location": "Lahore, Punjab" },
    { "name": "Lahore School of Economics (LSE)", "location": "Lahore, Punjab" },
    { "name": "Muhammad Ali Jinnah University (MAJU)", "location": "Karachi, Sindh" },
    { "name": "Riphah International University (RIU)", "location": "Islamabad, Federal" },
    { "name": "Greenwich University (GU)", "location": "Karachi, Sindh" },
    { "name": "Sir Syed University of Engineering and Technology (SSUET)", "location": "Karachi, Sindh" },
    { "name": "Superior University (SU)", "location": "Lahore, Punjab" },
    { "name": "University of South Asia (USA)", "location": "Lahore, Punjab" },
    { "name": "Iqra National University (INU)", "location": "Peshawar, Khyber Pakhtunkhwa" },
    { "name": "Sarhad University of Science and Information Technology (SUIT)", "location": "Peshawar, Khyber Pakhtunkhwa" },
    { "name": "Foundation University Islamabad (FUI)", "location": "Islamabad, Federal" },
    { "name": "Preston University (PU)", "location": "Islamabad, Federal" },
    { "name": "Beaconhouse National University (BNU)", "location": "Lahore, Punjab" },
    { "name": "Kinnaird College for Women (KCW)", "location": "Lahore, Punjab" },
    { "name": "Liaquat University of Medical and Health Sciences (LUMHS)", "location": "Jamshoro, Sindh" },
    { "name": "Peoples University of Medical and Health Sciences for Women (PUMHSW)", "location": "Nawabshah, Sindh" },
    { "name": "Karachi Institute of Economics and Technology (KIET)", "location": "Karachi, Sindh" }
];

export default universities;
